version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  whoami1:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami1.localhost

  whoami2:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami2.localhost